Introduce a check for bugs in answer-testing code to CI
We generally expect an answer-test to fail for one of 3 reasons:
  1. A change was made to Enzo-E or one of its dependencies that changed the actual answer.
  2. A new answer-test was introduced (and the older gold-standard doesn't produce an answer to test against)
  3. The answer-test itself was modified and the information checked by the answer test has changed.

If we expected the answer-tests to fail for one of the above reasons, then we generally want to update the gold-standard. However, there is a fourth reason the answer test may fail - if a change was introduced to the answer-testing code that broke an existing test.

This introduces a change to explicitly check that this last case isn't a problem. When the answer-test fails, we will now regenerate the answer tests using the currently checked out version of the code and we will confirm that the answer tests pass while using that version.

To confirm that this change works as intended, I have intentionally changed the gold-standard mentioned in the circleci file to an old version. I will update revert it after I confirm the code works as expected.

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -276,7 +276,7 @@ jobs:
             - run: echo "starting steps for pytest answer generation"
             - compile-enzoe:
                 usedouble: << parameters.usedouble >>
-                tag: gold-standard-004
+                tag: gold-standard-003
                 skipfile: notafile
                 usegrackle: << parameters.usegrackle >>
             - run-answer-tests:
@@ -299,6 +299,46 @@ jobs:
                 usedouble: << parameters.usedouble >>
                 usegrackle: << parameters.usegrackle >>
                 generate: false
+            - run:
+                name:  PostFailure Verfication that answer-tests pass when compared to answers generated by the same version
+                when: on_fail
+                command: |
+                  echo "Following the failure of answer tests, we now confirm "
+                  echo "that the pytest code itself works in the currently "
+                  echo "checked out branch. We do this by regenerating the "
+                  echo "answer-test answers and confirming that the the tests "
+                  echo "pass while using those same answers"
+
+                  # we might want to factor out the following logic (and the
+                  # previous step into an external bash script since their's a
+                  # lot of reused code... There's no other way to do this while
+                  # having this test run on failure...)
+                  #
+                  # Alternatively, after we merge PR #318, we should be able to
+                  # significantly simplify these 2 steps
+
+                  source $BASH_ENV
+                  source $HOME/venv/bin/activate
+
+                  # do a little setup based on the value of usegrackle:
+                  # 1. convert the parameter to an env var storing 0 or 1
+                  # 2. if that var holds true, export GRACKLE_INPUT_DATA_DIR
+                  USE_GRACKLE=$(( 0 <<# parameters.usegrackle >> + 1 <</ parameters.usegrackle >> ))
+                  if [[ $USE_GRACKLE == 1 ]]; then
+                    export GRACKLE_INPUT_DATA_DIR="$HOME/grackle/grackle_data_files/input/"
+                  fi
+
+                  export TEST_RESULTS_DIR="~/enzoe_test_results-selfconsistency"
+                  export USE_DOUBLE=<< parameters.usedouble >>
+
+                  echo "generate the test results"
+                  export GENERATE_TEST_RESULTS="true"
+                  pytest test/answer_tests
+                  if [ $? -ne 0 ]; then exit 1; fi
+
+                  echo "testing the new test results"
+                  export GENERATE_TEST_RESULTS="false"
+                  pytest test/answer_tests
 
       - when:
          condition:
